### ISSUE TITLE
Metallic mesh mod?

### ISSUE THREAD

**Issue by lucapandolfini** [Digitelektro/BackfireHelix#3]
Hello, forgive the naive question, but I noticed in one picture of yours that you installed a metallic mesh net on the dish together with the helical feed. 
Indeed it makes sense since the circularly polarised signal is not reflected in the vertical component of the dish, that has very few, sparse horizontal lines. 
In my case, without this modification, a properly tuned 1.7GHz helical feed performs *worse* than the original wifi feed (with the apical reflector reversed). 
Is it something to be expected?

**Comment by Digitelektro** [comment]
Hi! Good question! I think it is something to be expected. I might need to update the readme with this info. Since I covered with my dish long before this backfire helix feed was created, I didn't even think about this. 
On which satellite do you test the feed?

**Comment by lucapandolfini** [comment]
I tested it on the Elektro-L2 GGAK-E signal. I did not find any info regarding whether it is indeed circularly polarized or not, though.

**Comment by Digitelektro** [comment]
Elektro-L2 GGAK is circular polarized. Can you cover you dish with mesh and test it again please?

**Comment by lucapandolfini** [comment]
Hi thanks for the reply!

Unfortunately at the moment I do not have access to the dish, I will
make some tests and send my results in a couple of weeks.
Which mesh do you use?

 On Wed, 2024-07-24 at 03:00 -0700, Digitelektro wrote:
> Elektro-L2 GGAK is circular polarized. Can you cover you dish with
> mesh and test it again please?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>

-- 
Luca Pandolfini
Researcher
-------------------------------------
Istituto Italiano di Tecnologia - IIT
Center for Human Technologies (CHT)
Tower B, Erzelli Science Park 
Via Enrico Melen 83
16152 Genova, Italy

**Comment by Digitelektro** [comment]
Okay, no hurry!
The mesh I use is what I found in a local hardware store, it is a ~5mm spacing mesh, nothing special.

**Comment by lucapandolfini** [comment]
Ok, after some tests, I can confirm that the helix works better than the linear feed after installing a 5mm metallic mesh. I think it might be worth mentioning it in the readme. Thank you!

**Comment by Digitelektro** [comment]
Thanks for testing it! I updated the readme.
